title: Carlos' Notes
description: A collection of notes, thoughts, and ideas.
# theme: relearn

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
languageCode: en-us
relativeURLs: true

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
    extensions:
      gfm: true
  highlight:
    style: tango

outputs:
  home: [HTML, RSS, print]
  section: [HTML, RSS, print]
  page: [HTML, RSS, print]
