---
baseURL: "http://localhost"
languageCode: en-us
title: Carlos' Notes
theme: relearn

enableEmoji: true
enableGitInfo: true
relativeURLs: true

outputs:
  home:
    - HTML
    - RSS
    - SEARCH
    - SEARCHPAGE
  section: ["HTML", "RSS", "PRINT"]
  page: ["HTML", "RSS", "PRINT"]
