baseURL: http://localhost
title: digitalroots wiki
description: A collection of notes, thoughts, and ideas.
# theme: relearn

enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
languageCode: en-us
relativeURLs: true

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
    extensions:
      gfm: true
  highlight:
    noClasses: false  # https://www.docsy.dev/docs/adding-content/lookandfeel/#lightdark-color-themes
    style: tango

outputs:
  home: [HTML, RSS, print]
  section: [HTML, RSS, print]
  page: [HTML, RSS, print]
