copyright:
  authors: >-
    digitalroots |
    [CC BY 4.0](https://creativecommons.org/licenses/by/4.0)
  from_year: 2014
github_repo: https://github.com/drts01/notes
offlineSearch: true
navbar_logo: true
ui:
  sidebar_cache_limit: 100
  sidebar_menu_compact: true
  sidebar_menu_foldable: true
  ul_show: 1
